version: '3'

services:
  db:
    container_name: database
    env_file:
      - ./dev.env
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '5431:5432'

  auth:
    container_name: ratr_auth
    env_file:
      - ./dev.env
    build:
      context: ../
      dockerfile: docker/auth/Dockerfile
    depends_on:
      - db
    ports:
      - '5001:5000'
